export const API_URL = 'http://localhost:7000';

export const FETCH_ITEM_REQUEST = 'FETCH_ITEM_REQUEST';
export const FETCH_ITEM_SUCCESS = 'FETCH_ITEM_SUCCESS';
export const FETCH_ITEM_FAILURE = 'FETCH_ITEM_FAILURE';

export const IS_LOADING = 'IS_LOADING';

export const FETCH_ITEM_DETAIL_REQUEST = 'FETCH_ITEM_DETAIL_REQUEST';
export const FETCH_ITEM_DETAIL_SUCCESS = 'FETCH_ITEM_DETAIL_SUCCESS';
export const FETCH_ITEM_DETAIL_FAILURE = 'FETCH_ITEM_DETAIL_FAILURE';
